apiVersion: v1
kind: Service # To expose MySQL to other services, here zkubernetes app
metadata:
  name: mysql  # DNS name
  labels:
    app: mysql
    tier: database
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:       # MySQL pod labels
    app: mysql
    tier: database
  clusterIP: None  # We use DNS, thus ClusterIP is not relevant here