apiVersion: v1
kind: Service
metadata:
  name: zkubernetes-service
spec:
  selector:
    app: zkubernetes
  ports:
    - protocol: "TCP"
      port: 8080 # The port that the service is running on in the cluster
      targetPort: 8080 # The port exposed by the service
  type: NodePort # service type